// Code generated by goctl. DO NOT EDIT.
// Source: mysqlmanage.proto

package server

import (
	"context"

	"SimpleTikTok/internal/MicroServices/mysqlmanage/internal/logic"
	"SimpleTikTok/internal/MicroServices/mysqlmanage/internal/svc"
	"SimpleTikTok/internal/MicroServices/mysqlmanage/pkg/MySQLManageServer"
)

type MySQLManageServerServer struct {
	svcCtx *svc.ServiceContext
	MySQLManageServer.UnimplementedMySQLManageServerServer
}

func NewMySQLManageServerServer(svcCtx *svc.ServiceContext) *MySQLManageServerServer {
	return &MySQLManageServerServer{
		svcCtx: svcCtx,
	}
}

func (s *MySQLManageServerServer) GetMySQL(ctx context.Context, in *MySQLManageServer.IdRequest) (*MySQLManageServer.MySQLResponse, error) {
	l := logic.NewGetMySQLLogic(ctx, s.svcCtx)
	return l.GetMySQL(in)
}
