// Code generated by goctl. DO NOT EDIT.
package types

type FeedHandlerRequest struct {
	LastestTime int64  `form:"lastest_time"`
	Token       string `form:"token"`
}

type FeedHandlerResponse struct {
	StatusCode int32   `json:"status_code"`
	StatusMsg  string  `json:"status_msg"`
	VideoList  []Video `json:"video_list"`
	NextTime   int64   `json:"next_time"` // 获取到的视频中，最早的投稿时间
}

type UserHandlerRequest struct {
	UserID int64  `form:"user_id"`
	Token  string `form:"token"`
}

type UserHandlerResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	User       User   `json:"user"`
}

type UserloginHandlerRequest struct {
	UserName string `form:"username"`
	PassWord string `form:"password"`
}

type UserloginHandlerResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	Token      string `json:"token"`
	UserID     int64  `json:"user_id"`
}

type PublishActionHandlerRequest struct {
	Token string `form:"token"`
	Title string `form:"title"`
}

type PublishActionHandlerResponse struct {
	StatusCode int32  `json:"status_code,default=400"`
	StatusMsg  string `json:"status_msg,optional"`
}

type PublishListHandlerRequest struct {
	UserID int64  `form:"user_id"`
	Token  string `form:"token"`
}

type PublishListHandlerResponse struct {
	StatusCode int32   `json:"status_code"`
	StatusMsg  string  `json:"status_msg"`
	VideoList  []Video `json:"video_list"`
}

type Video struct {
	Id            int64  `form:"id"`
	Author        User   `form:"author"`
	PlayUrl       string `form:"play_url"`
	CoverUrl      string `form:"cover_url"`
	FavoriteCount int64  `form:"favorite_count"`
	CommentCount  int64  `form:"comment_count"`
	IsFavotite    bool   `form:"is_favorite"`
	VideoTitle    string `form:"video_title"`
}

type User struct {
	UserId        int64  `gorm:"column:user_id"        json:"id"               form:"user_id"        bson:"user_id"`
	Name          string `gorm:"column:user_nick_name" json:"name"             form:"name"           bson:"name"`
	FollowCount   int64  `gorm:"column:follow_count"   json:"follow_count"     form:"follow_count"   bson:"follow_count"`
	FollowerCount int64  `gorm:"column:follower_count" json:"follower_count"   form:"follower_count" bson:"follower_count"`
	IsFollow      bool   `json:"is_follow"             form:"is_follow"        bson:"is_follow"`
}
