// Code generated by goctl. DO NOT EDIT.
// Source: mysqlmanage.proto

package server

import (
	"context"

	"SimpleTikTok/internal_proto/microservices/mysqlmanage/internal/logic"
	"SimpleTikTok/internal_proto/microservices/mysqlmanage/internal/svc"
	"SimpleTikTok/internal_proto/microservices/mysqlmanage/pkg/MySQLManageServer"
)

type MySQLManageServerServer struct {
	svcCtx *svc.ServiceContext
	MySQLManageServer.UnimplementedMySQLManageServerServer
}

func NewMySQLManageServerServer(svcCtx *svc.ServiceContext) *MySQLManageServerServer {
	return &MySQLManageServerServer{
		svcCtx: svcCtx,
	}
}

// 1
func (s *MySQLManageServerServer) CommentGetUserByUserId(ctx context.Context, in *MySQLManageServer.CommentGetUserByUserIdRequest) (*MySQLManageServer.CommentGetUserByUserIdResponse, error) {
	l := logic.NewCommentGetUserByUserIdLogic(ctx, s.svcCtx)
	return l.CommentGetUserByUserId(in)
}

// 2
func (s *MySQLManageServerServer) FavoriteVideoNum(ctx context.Context, in *MySQLManageServer.FavoriteVideoNumRequest) (*MySQLManageServer.FavoriteVideoNumResponse, error) {
	l := logic.NewFavoriteVideoNumLogic(ctx, s.svcCtx)
	return l.FavoriteVideoNum(in)
}
