// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	RelationFollowInterface "SimpleTikTok/external_api/relationfollow/internal/handler/RelationFollowInterface"
	"SimpleTikTok/external_api/relationfollow/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/douyin/relation/action",
				Handler: RelationFollowInterface.RelationActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/relation/follow/list",
				Handler: RelationFollowInterface.RelationFollowListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/relation/follower/list",
				Handler: RelationFollowInterface.RelationFollowerListHandler(serverCtx),
			},
		},
	)
}
