// Code generated by goctl. DO NOT EDIT.
// Source: mysqlmanage.proto

package mysqlmanageserverclient

import (
	"context"

	"SimpleTikTok/internal_proto/microservices/mysqlmanage/pkg/MySQLManageServer"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentGetUserByUserIdRequest  = MySQLManageServer.CommentGetUserByUserIdRequest
	CommentGetUserByUserIdResponse = MySQLManageServer.CommentGetUserByUserIdResponse
	FavoriteVideoNumRequest        = MySQLManageServer.FavoriteVideoNumRequest
	FavoriteVideoNumResponse       = MySQLManageServer.FavoriteVideoNumResponse

	MySQLManageServer interface {
		// 1
		CommentGetUserByUserId(ctx context.Context, in *CommentGetUserByUserIdRequest, opts ...grpc.CallOption) (*CommentGetUserByUserIdResponse, error)
		// 2
		FavoriteVideoNum(ctx context.Context, in *FavoriteVideoNumRequest, opts ...grpc.CallOption) (*FavoriteVideoNumResponse, error)
	}

	defaultMySQLManageServer struct {
		cli zrpc.Client
	}
)

func NewMySQLManageServer(cli zrpc.Client) MySQLManageServer {
	return &defaultMySQLManageServer{
		cli: cli,
	}
}

// 1
func (m *defaultMySQLManageServer) CommentGetUserByUserId(ctx context.Context, in *CommentGetUserByUserIdRequest, opts ...grpc.CallOption) (*CommentGetUserByUserIdResponse, error) {
	client := MySQLManageServer.NewMySQLManageServerClient(m.cli.Conn())
	return client.CommentGetUserByUserId(ctx, in, opts...)
}

// 2
func (m *defaultMySQLManageServer) FavoriteVideoNum(ctx context.Context, in *FavoriteVideoNumRequest, opts ...grpc.CallOption) (*FavoriteVideoNumResponse, error) {
	client := MySQLManageServer.NewMySQLManageServerClient(m.cli.Conn())
	return client.FavoriteVideoNum(ctx, in, opts...)
}
