// Code generated by goctl. DO NOT EDIT.
// Source: mysql.proto

package mysqlclient

import (
	"context"

	"SimpleTikTok/internal/MicroServices/pkg/MySQL"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IdRequest     = MySQL.IdRequest
	MySQLResponse = MySQL.MySQLResponse

	MySQL interface {
		GetMySQL(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*MySQLResponse, error)
	}

	defaultMySQL struct {
		cli zrpc.Client
	}
)

func NewMySQL(cli zrpc.Client) MySQL {
	return &defaultMySQL{
		cli: cli,
	}
}

func (m *defaultMySQL) GetMySQL(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*MySQLResponse, error) {
	client := MySQL.NewMySQLClient(m.cli.Conn())
	return client.GetMySQL(ctx, in, opts...)
}
