// Code generated by goctl. DO NOT EDIT.
// Source: mysqlmanage.proto

package mysqlmanageserverclient

import (
	"context"

	"SimpleTikTok/internal/microservices/mysqlmanage/pkg/MySQLManageServer"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IdRequest     = MySQLManageServer.IdRequest
	MySQLResponse = MySQLManageServer.MySQLResponse

	MySQLManageServer interface {
		GetMySQL(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*MySQLResponse, error)
	}

	defaultMySQLManageServer struct {
		cli zrpc.Client
	}
)

func NewMySQLManageServer(cli zrpc.Client) MySQLManageServer {
	return &defaultMySQLManageServer{
		cli: cli,
	}
}

func (m *defaultMySQLManageServer) GetMySQL(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*MySQLResponse, error) {
	client := MySQLManageServer.NewMySQLManageServerClient(m.cli.Conn())
	return client.GetMySQL(ctx, in, opts...)
}
