// Code generated by goctl. DO NOT EDIT.
// Source: mysql.proto

package server

import (
	"context"

	"SimpleTikTok/internal/MicroServices/mysql/internal/logic"
	"SimpleTikTok/internal/MicroServices/mysql/internal/svc"
	"SimpleTikTok/internal/MicroServices/pkg/MySQL"
)

type MySQLServer struct {
	svcCtx *svc.ServiceContext
	MySQL.UnimplementedMySQLServer
}

func NewMySQLServer(svcCtx *svc.ServiceContext) *MySQLServer {
	return &MySQLServer{
		svcCtx: svcCtx,
	}
}

func (s *MySQLServer) GetMySQL(ctx context.Context, in *MySQL.IdRequest) (*MySQL.MySQLResponse, error) {
	l := logic.NewGetMySQLLogic(ctx, s.svcCtx)
	return l.GetMySQL(in)
}
