// Code generated by goctl. DO NOT EDIT.
// Source: minio.proto

package server

import (
	"context"

	"SimpleTikTok/internal/MicroServices/minio/internal/logic"
	"SimpleTikTok/internal/MicroServices/minio/internal/svc"
	"SimpleTikTok/internal/MicroServices/pkg/Minio"
)

type MinioServer struct {
	svcCtx *svc.ServiceContext
	Minio.UnimplementedMinioServer
}

func NewMinioServer(svcCtx *svc.ServiceContext) *MinioServer {
	return &MinioServer{
		svcCtx: svcCtx,
	}
}

func (s *MinioServer) GetMinio(ctx context.Context, in *Minio.IdRequest) (*Minio.MinioResponse, error) {
	l := logic.NewGetMinioLogic(ctx, s.svcCtx)
	return l.GetMinio(in)
}
