// Code generated by goctl. DO NOT EDIT.
// Source: miniomanage.proto

package miniomanageserverclient

import (
	"context"

	"SimpleTikTok/internal/MicroServices/miniomanage/pkg/MinioManageServer"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMinioConnectRequest     = MinioManageServer.GetMinioConnectRequest
	GetMinioConnectResponse    = MinioManageServer.GetMinioConnectResponse
	PutFileUploaderByteRequest = MinioManageServer.PutFileUploaderByteRequest
	PutFileUploaderByteponse   = MinioManageServer.PutFileUploaderByteponse
	PutFileUploaderRequest     = MinioManageServer.PutFileUploaderRequest
	PutFileUploaderResponse    = MinioManageServer.PutFileUploaderResponse

	MinioManageServer interface {
		// 文件上传
		PutFileUploader(ctx context.Context, in *PutFileUploaderRequest, opts ...grpc.CallOption) (*PutFileUploaderResponse, error)
		// byte形式文件上传
		PutFileUploaderByte(ctx context.Context, in *PutFileUploaderByteRequest, opts ...grpc.CallOption) (*PutFileUploaderByteponse, error)
		// 文件下载
		GetFileUploader(ctx context.Context, in *GetMinioConnectRequest, opts ...grpc.CallOption) (*GetMinioConnectResponse, error)
	}

	defaultMinioManageServer struct {
		cli zrpc.Client
	}
)

func NewMinioManageServer(cli zrpc.Client) MinioManageServer {
	return &defaultMinioManageServer{
		cli: cli,
	}
}

// 文件上传
func (m *defaultMinioManageServer) PutFileUploader(ctx context.Context, in *PutFileUploaderRequest, opts ...grpc.CallOption) (*PutFileUploaderResponse, error) {
	client := MinioManageServer.NewMinioManageServerClient(m.cli.Conn())
	return client.PutFileUploader(ctx, in, opts...)
}

// byte形式文件上传
func (m *defaultMinioManageServer) PutFileUploaderByte(ctx context.Context, in *PutFileUploaderByteRequest, opts ...grpc.CallOption) (*PutFileUploaderByteponse, error) {
	client := MinioManageServer.NewMinioManageServerClient(m.cli.Conn())
	return client.PutFileUploaderByte(ctx, in, opts...)
}

// 文件下载
func (m *defaultMinioManageServer) GetFileUploader(ctx context.Context, in *GetMinioConnectRequest, opts ...grpc.CallOption) (*GetMinioConnectResponse, error) {
	client := MinioManageServer.NewMinioManageServerClient(m.cli.Conn())
	return client.GetFileUploader(ctx, in, opts...)
}
