// Code generated by goctl. DO NOT EDIT.
package types

type UserRegisterHandlerRequest struct {
	UserName string `form:"username"`
	PassWord string `form:"password"`
}

type UserRegisterHandlerResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	Token      string `json:"token"`
	UserID     int64  `json:"user_id"`
}
