// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/mongodbmanage.proto

package mongodbmanageserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MongodbManageServerClient is the client API for MongodbManageServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MongodbManageServerClient interface {
	GetMinio(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*MinioResponse, error)
}

type mongodbManageServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMongodbManageServerClient(cc grpc.ClientConnInterface) MongodbManageServerClient {
	return &mongodbManageServerClient{cc}
}

func (c *mongodbManageServerClient) GetMinio(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*MinioResponse, error) {
	out := new(MinioResponse)
	err := c.cc.Invoke(ctx, "/mongodbmanageserver.MongodbManageServer/getMinio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MongodbManageServerServer is the server API for MongodbManageServer service.
// All implementations must embed UnimplementedMongodbManageServerServer
// for forward compatibility
type MongodbManageServerServer interface {
	GetMinio(context.Context, *IdRequest) (*MinioResponse, error)
	mustEmbedUnimplementedMongodbManageServerServer()
}

// UnimplementedMongodbManageServerServer must be embedded to have forward compatible implementations.
type UnimplementedMongodbManageServerServer struct {
}

func (UnimplementedMongodbManageServerServer) GetMinio(context.Context, *IdRequest) (*MinioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMinio not implemented")
}
func (UnimplementedMongodbManageServerServer) mustEmbedUnimplementedMongodbManageServerServer() {}

// UnsafeMongodbManageServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MongodbManageServerServer will
// result in compilation errors.
type UnsafeMongodbManageServerServer interface {
	mustEmbedUnimplementedMongodbManageServerServer()
}

func RegisterMongodbManageServerServer(s grpc.ServiceRegistrar, srv MongodbManageServerServer) {
	s.RegisterService(&MongodbManageServer_ServiceDesc, srv)
}

func _MongodbManageServer_GetMinio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongodbManageServerServer).GetMinio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongodbmanageserver.MongodbManageServer/getMinio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongodbManageServerServer).GetMinio(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MongodbManageServer_ServiceDesc is the grpc.ServiceDesc for MongodbManageServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MongodbManageServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongodbmanageserver.MongodbManageServer",
	HandlerType: (*MongodbManageServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getMinio",
			Handler:    _MongodbManageServer_GetMinio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mongodbmanage.proto",
}
