// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	RegisterInterface "SimpleTikTok/external_api/registerinterface/internal/handler/RegisterInterface"
	"SimpleTikTok/external_api/registerinterface/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/douyin/user/register",
				Handler: RegisterInterface.UserRegisterHandler(serverCtx),
			},
		},
	)
}
