// Code generated by goctl. DO NOT EDIT.
// Source: utilserver.proto

package utilserverclient

import (
	"context"

	"SimpleTikTok/internal_proto/microservices/utilserver/types/utilserver"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IdRequest     = utilserver.IdRequest
	MinioResponse = utilserver.MinioResponse

	Utilserver interface {
		GetMinio(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*MinioResponse, error)
	}

	defaultUtilserver struct {
		cli zrpc.Client
	}
)

func NewUtilserver(cli zrpc.Client) Utilserver {
	return &defaultUtilserver{
		cli: cli,
	}
}

func (m *defaultUtilserver) GetMinio(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*MinioResponse, error) {
	client := utilserver.NewUtilserverClient(m.cli.Conn())
	return client.GetMinio(ctx, in, opts...)
}
