// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/mysql.proto

package MySQL

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MySQLClient is the client API for MySQL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MySQLClient interface {
	GetMySQL(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*MySQLResponse, error)
}

type mySQLClient struct {
	cc grpc.ClientConnInterface
}

func NewMySQLClient(cc grpc.ClientConnInterface) MySQLClient {
	return &mySQLClient{cc}
}

func (c *mySQLClient) GetMySQL(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*MySQLResponse, error) {
	out := new(MySQLResponse)
	err := c.cc.Invoke(ctx, "/MySQL.MySQL/getMySQL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MySQLServer is the server API for MySQL service.
// All implementations must embed UnimplementedMySQLServer
// for forward compatibility
type MySQLServer interface {
	GetMySQL(context.Context, *IdRequest) (*MySQLResponse, error)
	mustEmbedUnimplementedMySQLServer()
}

// UnimplementedMySQLServer must be embedded to have forward compatible implementations.
type UnimplementedMySQLServer struct {
}

func (UnimplementedMySQLServer) GetMySQL(context.Context, *IdRequest) (*MySQLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMySQL not implemented")
}
func (UnimplementedMySQLServer) mustEmbedUnimplementedMySQLServer() {}

// UnsafeMySQLServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MySQLServer will
// result in compilation errors.
type UnsafeMySQLServer interface {
	mustEmbedUnimplementedMySQLServer()
}

func RegisterMySQLServer(s grpc.ServiceRegistrar, srv MySQLServer) {
	s.RegisterService(&MySQL_ServiceDesc, srv)
}

func _MySQL_GetMySQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLServer).GetMySQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MySQL.MySQL/getMySQL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLServer).GetMySQL(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MySQL_ServiceDesc is the grpc.ServiceDesc for MySQL service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MySQL_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MySQL.MySQL",
	HandlerType: (*MySQLServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getMySQL",
			Handler:    _MySQL_GetMySQL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mysql.proto",
}
