// Code generated by goctl. DO NOT EDIT.
// Source: utilserver.proto

package server

import (
	"context"

	"SimpleTikTok/internal/microservices/utilserver/internal/logic"
	"SimpleTikTok/internal/microservices/utilserver/internal/svc"
	"SimpleTikTok/internal/microservices/utilserver/pkg/Utilserver"
)

type UtilserverServer struct {
	svcCtx *svc.ServiceContext
	Utilserver.UnimplementedUtilserverServer
}

func NewUtilserverServer(svcCtx *svc.ServiceContext) *UtilserverServer {
	return &UtilserverServer{
		svcCtx: svcCtx,
	}
}

func (s *UtilserverServer) GetMinio(ctx context.Context, in *Utilserver.IdRequest) (*Utilserver.MinioResponse, error) {
	l := logic.NewGetMinioLogic(ctx, s.svcCtx)
	return l.GetMinio(in)
}
