// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/mysqlmanage.proto

package MySQLManageServer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentGetUserByUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *CommentGetUserByUserIdRequest) Reset() {
	*x = CommentGetUserByUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mysqlmanage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentGetUserByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentGetUserByUserIdRequest) ProtoMessage() {}

func (x *CommentGetUserByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mysqlmanage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentGetUserByUserIdRequest.ProtoReflect.Descriptor instead.
func (*CommentGetUserByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_mysqlmanage_proto_rawDescGZIP(), []int{0}
}

func (x *CommentGetUserByUserIdRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CommentGetUserByUserIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// CommentUser gender = 1;
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CommentGetUserByUserIdResponse) Reset() {
	*x = CommentGetUserByUserIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mysqlmanage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentGetUserByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentGetUserByUserIdResponse) ProtoMessage() {}

func (x *CommentGetUserByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mysqlmanage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentGetUserByUserIdResponse.ProtoReflect.Descriptor instead.
func (*CommentGetUserByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_mysqlmanage_proto_rawDescGZIP(), []int{1}
}

func (x *CommentGetUserByUserIdResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FavoriteVideoNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *FavoriteVideoNumRequest) Reset() {
	*x = FavoriteVideoNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mysqlmanage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavoriteVideoNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteVideoNumRequest) ProtoMessage() {}

func (x *FavoriteVideoNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mysqlmanage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteVideoNumRequest.ProtoReflect.Descriptor instead.
func (*FavoriteVideoNumRequest) Descriptor() ([]byte, []int) {
	return file_proto_mysqlmanage_proto_rawDescGZIP(), []int{2}
}

func (x *FavoriteVideoNumRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FavoriteVideoNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// CommentUser gender = 1;
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FavoriteVideoNumResponse) Reset() {
	*x = FavoriteVideoNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mysqlmanage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FavoriteVideoNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteVideoNumResponse) ProtoMessage() {}

func (x *FavoriteVideoNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mysqlmanage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteVideoNumResponse.ProtoReflect.Descriptor instead.
func (*FavoriteVideoNumResponse) Descriptor() ([]byte, []int) {
	return file_proto_mysqlmanage_proto_rawDescGZIP(), []int{3}
}

func (x *FavoriteVideoNumResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_mysqlmanage_proto protoreflect.FileDescriptor

var file_proto_mysqlmanage_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x4d, 0x79, 0x53, 0x51, 0x4c,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x37, 0x0a, 0x1d,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x1e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x31, 0x0a,
	0x17, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4e, 0x75,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x30, 0x0a, 0x18, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0xff, 0x01, 0x0a, 0x11, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x7d, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x30, 0x2e, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x10, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x69, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4e, 0x75, 0x6d, 0x12, 0x2a, 0x2e, 0x4d, 0x79,
	0x53, 0x51, 0x4c, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4e, 0x75, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x46, 0x61, 0x76, 0x6f,
	0x72, 0x69, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_mysqlmanage_proto_rawDescOnce sync.Once
	file_proto_mysqlmanage_proto_rawDescData = file_proto_mysqlmanage_proto_rawDesc
)

func file_proto_mysqlmanage_proto_rawDescGZIP() []byte {
	file_proto_mysqlmanage_proto_rawDescOnce.Do(func() {
		file_proto_mysqlmanage_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mysqlmanage_proto_rawDescData)
	})
	return file_proto_mysqlmanage_proto_rawDescData
}

var file_proto_mysqlmanage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_mysqlmanage_proto_goTypes = []interface{}{
	(*CommentGetUserByUserIdRequest)(nil),  // 0: MySQLManageServer.CommentGetUserByUserIdRequest
	(*CommentGetUserByUserIdResponse)(nil), // 1: MySQLManageServer.CommentGetUserByUserIdResponse
	(*FavoriteVideoNumRequest)(nil),        // 2: MySQLManageServer.FavoriteVideoNumRequest
	(*FavoriteVideoNumResponse)(nil),       // 3: MySQLManageServer.FavoriteVideoNumResponse
}
var file_proto_mysqlmanage_proto_depIdxs = []int32{
	0, // 0: MySQLManageServer.MySQLManageServer.CommentGetUserByUserId:input_type -> MySQLManageServer.CommentGetUserByUserIdRequest
	2, // 1: MySQLManageServer.MySQLManageServer.FavoriteVideoNum:input_type -> MySQLManageServer.FavoriteVideoNumRequest
	1, // 2: MySQLManageServer.MySQLManageServer.CommentGetUserByUserId:output_type -> MySQLManageServer.CommentGetUserByUserIdResponse
	3, // 3: MySQLManageServer.MySQLManageServer.FavoriteVideoNum:output_type -> MySQLManageServer.FavoriteVideoNumResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mysqlmanage_proto_init() }
func file_proto_mysqlmanage_proto_init() {
	if File_proto_mysqlmanage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mysqlmanage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentGetUserByUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mysqlmanage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentGetUserByUserIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mysqlmanage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavoriteVideoNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mysqlmanage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FavoriteVideoNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mysqlmanage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mysqlmanage_proto_goTypes,
		DependencyIndexes: file_proto_mysqlmanage_proto_depIdxs,
		MessageInfos:      file_proto_mysqlmanage_proto_msgTypes,
	}.Build()
	File_proto_mysqlmanage_proto = out.File
	file_proto_mysqlmanage_proto_rawDesc = nil
	file_proto_mysqlmanage_proto_goTypes = nil
	file_proto_mysqlmanage_proto_depIdxs = nil
}
